name: umc dev CI/CD

on:
  pull_request:
    types: [closed] #merege가 됐을때 돌아라
  workflow_dispatch: # (2).수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: github.event.pull_request.merged == ture && github.event.pull_request.base.ref == 'dev'
    # dev에 머지되었으면 돌아라

    steps:
    - name: Checkout #build할 코드를 가져오는것(이름은 정형화 된것이 아니라 마음대로해도됨)
      uses: actions/checkout@v2 #(4).코드 check out

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17 # (5). 자바 설치
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod -x ./gradlew
      shell: bash #(6).권한 부여

    - name: Build With Gradle
      run: ./gradlew clean build -x test
      shell: bash #(7).build 시작

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00" #(8).build 시점의 시간 확보

    - name: Show Current Time
      run: echo "CurrentTime=$"
      shell: bash #(9).확보한 시간 보여주기

    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cp -r .platform deploy/.platform
        cd deploy && zip -r deploy.zip .

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: